---
  - name: INSTALL virtualenv via pip3.6
    pip:
      name: virtualenv
      executable: pip3.6

  - name: Create NvIPAM venv 
    become: yes
    become_user: nvipam
    pip:
      name: 
        - flask
        - uwsgi
      virtualenv: /home/nvipam/nvipam/venv
      virtualenv_python: /bin/python3.6
    environment:
      PATH: "{{ ansible_env.PATH }}"

  - name: Install NvIPAM pip requirements 
    become: yes
    become_user: nvipam
    pip:
      requirements: /home/nvipam/nvipam/requirements.txt
      virtualenv: /home/nvipam/nvipam/venv
#     environment:
#       PATH: "{{ ansible_env.PATH }}"

  - name: copy pyvenv file to venv
    copy:
      src: files/pyvenv
      dest: /home/nvipam/nvipam/venv/bin/pyvenv
      owner: nvipam
      group: nvipam
      mode: 0755
