---
- name: Install core NvIPAM components
  hosts: all
  vars_files:
    - vars/all
  tasks:
  - name: Install EPEL
    yum:
      name: epel-release
      state: present

  - name: Install libselinux-python
    yum:
      name: libselinux-python
      state: present

  - name: Install Python3.6
    yum:
      name: python36
      state: present

  - name: Install git
    yum:
      name: git
      state: present

  roles:
    - role: geerlingguy.postgresql
     
