---
  - name: Copy recursor.conf to fix issue with imported role
    copy: src=files/recursor.conf dest=/etc/pdns-recursor/recursor.conf 


  - name: RESTART Restarting pdns-recursor.service
    shell: systemctl restart pdns-recursor.service 
